const functions = require('firebase-functions')
const searchPerson = require('./searchPerson')
const sendEmailFeedback = require('./sendEmailFeedback')
const removeUser = require('./removeUser')
const setMessagingToken = require('./setMessagingToken')
const deleteMessagingToken = require('./deleteMessagingToken')
const getListFiles = require('./getListFiles')

exports.searchPerson = functions.https.onCall(searchPerson)
exports.sendEmailFeedback = functions.https.onCall(sendEmailFeedback)
exports.removeUser = functions.https.onCall(removeUser)
exports.setMessagingToken = functions.https.onCall(setMessagingToken)
exports.deleteMessagingToken = functions.https.onCall(deleteMessagingToken)
exports.getListFiles = functions.https.onCall(getListFiles)
